### ISSUE TITLE
just say tanks

### ISSUE THREAD

**Issue by alimd** [mozilla/web-forward#13]
sorry, its not an issue.
i want just say tanks to @pfinette for starting this project.
this project was my dream. and one day i do this im my country with my student and people.
thank you very much @pfinette and thanks mozilla.
I'll be very happy if I can any help.

**Comment by gitbiz** [comment]
hi Ali-
I just shared this with Pascal and we really appreciate your message. What country are you in?
Thank you so much for your interest in Mozilla and WebFWD!

Diane

**Comment by alimd** [comment]
@gitbiz i'm a web technology teacher in iran.
and iran have many many jennies developers but we usually in Boycott and my country busy in politics
fo example we can't work with other company like mozilla or google
Even when i open developer.google.com, google show an error for me : **We're sorry, but this service is not available in your country.**
But, One day, soon or late, I'll do it.
i trying to use github for running a simple webfwd in [this page](github.com/1schools-projects) with my current students
