### ISSUE TITLE
the "buzz" should include posts from webfwd projects

### ISSUE THREAD

**Issue by lloyd** [mozilla/web-forward#4]
Namely, we should have blog posts both from the webfwd site and from participating projects.  @lloyd will do this work, but needs from @pfinette an initial list of feed urls that we'd like to start with.

Also, these feeds should be easy to dynamically configure (a little json file?) and we should take an _excerpt_ of each, and merge them in chronological order.

**Comment by pfinette** [comment]
In terms of features (attention: FEATURE CREEP) it would be awesome if:
- We can pull the title and the first x words of the post.
- Link to the article by making both the title and a "more..." at the end of the excerpt <a href="...">
- Have an indicator where the post came from (where it currently says "x days ago" it should add the source, e.g. "x days ago from CASH Music")
